name: Terraform validator

# When to run this pipeline
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout to the PR branch
        uses: actions/checkout@v2

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      - name: Format the code
        id: fmt
        run: terraform fmt
